### ISSUE TITLE
Error when trying to save bookmark via bookmarklet

### ISSUE THREAD

**Issue by galfert** [skddc/webmarks#71]
I just tried to save a bookmark without a description, coming to Webmarks via the bookmarklet.

The bookmark was not saved, instead I got this error in the console:

```json
{
    "error": {
        "code": 0,
        "dataPath": "/description",
        "message": "Invalid type: null (expected string)",
        "params": {
            "expected": "string",
            "type": "null"
        },
        "schemaPath": "/properties/description/type",
        "stack": "Error\n    at new E (https://webmarks.5apps.com/assets/vendor-2fad33bee7f159b9b04b67027102f63b.js:4374:7)\n    at l.createError (https://webmarks.5apps.com/assets/vendor-2fad33bee7f159b9b04b67027102f63b.js:4258:235)\n    at l.validateType (https://webmarks.5apps.com/assets/vendor-2fad33bee7f159b9b04b67027102f63b.js:4307:71)\n    at l.validateBasic (https://webmarks.5apps.com/assets/vendor-2fad33bee7f159b9b04b67027102f63b.js:4301:15)\n    at l.validateAll (https://webmarks.5apps.com/assets/vendor-2fad33bee7f159b9b04b67027102f63b.js:4290:404)\n    at l.validateObjectProperties (https://webmarks.5apps.com/assets/vendor-2fad33bee7f159b9b04b67027102f63b.js:4338:66)\n    at l.validateObject (https://webmarks.5apps.com/assets/vendor-2fad33bee7f159b9b04b67027102f63b.js:4333:210)\n    at l.validateAll (https://webmarks.5apps.com/assets/vendor-2fad33bee7f159b9b04b67027102f63b.js:4290:515)\n    at Object.validate (https://webmarks.5apps.com/assets/vendor-2fad33bee7f159b9b04b67027102f63b.js:4385:9)\n    at Object.validateResult (https://webmarks.5apps.com/assets/vendor-2fad33bee7f159b9b04b67027102f63b.js:4387:22)",
        "subErrors": null
    },
    "missing": [],
    "valid": false
}
```

**Comment by skddc** [comment]
Confirmed. Sorry about that, it does work without a description on Android now tho. :clown_face:
